import React, { useState, useEffect } from 'react';

const ResultPDF = ({ selectedResult, onBack }) => {
  const [fullResult, setFullResult] = useState(null);
  const [snapshots, setSnapshots] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (selectedResult && selectedResult._id) {
      console.log('Fetching session data for:', selectedResult._id);
      fetch(`http://localhost:5000/ml/session/${selectedResult._id}`)
        .then(res => {
          console.log('Fetch response status:', res.status);
          if (!res.ok) {
            throw new Error(`HTTP error! status: ${res.status}`);
          }
          return res.json();
        })
        .then(data => {
          console.log('Fetched data:', data);
          setFullResult(data.session);
          setSnapshots(data.snapshots || []);
          setLoading(false);
        })
        .catch(err => {
          console.error('Error fetching session details:', err);
          setLoading(false);
        });
    } else {
      console.log('No selectedResult or _id:', selectedResult);
      setFullResult(selectedResult);
      setLoading(false);
    }
  }, [selectedResult]);

  if (loading) {
    return <div className="text-center mt-5">Loading report...</div>;
  }

  if (!fullResult) {
    return <div>No result selected</div>;
  }

  const { student_id: student, exam_id: exam, score, total_questions, violation_counts, login_time, logout_time, status, ml_screenshots } = fullResult;

  return (
    <div className="container mt-4">
      <div className="row">
        <div className="col-12">
          <div className="card">
            <div className="card-header bg-primary text-white d-flex justify-content-between align-items-center">
              <h4 className="mb-0">
                <i className="bi bi-file-earmark-pdf me-2"></i>
                ProctorAI Exam Report
              </h4>
              <button className="btn btn-light" onClick={onBack}>
                <i className="bi bi-arrow-left me-1"></i>Back
              </button>
            </div>
            <div className="card-body">
              <div className="text-center mb-4">
                <p className="text-muted">
                  <i className="bi bi-shield-check me-2" style={{ color: '#00A85A' }}></i>
                  This report was generated by ProctorAI on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
                </p>
                <h5 className="text-success fw-bold">ProctorAI - Advanced Proctoring System</h5>
              </div>

              <div className="row">
                <div className="col-md-6">
                  <div className="card mb-3">
                    <div className="card-header bg-info text-white">
                      <h6 className="mb-0"><i className="bi bi-person me-2"></i>Student Details</h6>
                    </div>
                    <div className="card-body">
                      <p><strong>Name:</strong> {student?.name || 'N/A'}</p>
                      <p><strong>Roll Number:</strong> {student?.roll_no || 'N/A'}</p>
                      <p><strong>Email:</strong> {student?.email || 'N/A'}</p>
                      <p><strong>Course:</strong> {student?.course || 'N/A'}</p>
                      <p><strong>Year:</strong> {student?.year || 'N/A'}</p>
                      {student?.photo_path && (
                        <p><strong>Photo:</strong> <img src={student.photo_path} alt="Student Photo" style={{width: '100px', height: '100px', objectFit: 'cover'}} /></p>
                      )}
                    </div>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card mb-3">
                    <div className="card-header bg-success text-white">
                      <h6 className="mb-0"><i className="bi bi-book me-2"></i>Exam Details</h6>
                    </div>
                    <div className="card-body">
                      <p><strong>Title:</strong> {exam?.title || 'N/A'}</p>
                      <p><strong>Subject:</strong> {exam?.subject || 'N/A'}</p>
                      <p><strong>Date:</strong> {exam?.date ? new Date(exam.date).toLocaleDateString() : 'N/A'}</p>
                      <p><strong>Duration:</strong> {exam?.duration ? `${exam.duration} minutes` : 'N/A'}</p>
                      <p><strong>Total Marks:</strong> {exam?.totalMarks || 'N/A'}</p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="row">
                <div className="col-md-6">
                  <div className="card mb-3">
                    <div className="card-header bg-warning text-dark">
                      <h6 className="mb-0"><i className="bi bi-clock me-2"></i>Session Details</h6>
                    </div>
                    <div className="card-body">
                      <p><strong>Login Time:</strong> {login_time ? new Date(login_time).toLocaleString() : 'N/A'}</p>
                      <p><strong>Logout Time:</strong> {logout_time ? new Date(logout_time).toLocaleString() : 'N/A'}</p>
                      <p><strong>Status:</strong> <span className={`badge ${status === 'completed' ? 'bg-success' : 'bg-warning'}`}>{status}</span></p>
                    </div>
                  </div>
                </div>
                <div className="col-md-6">
                  <div className="card mb-3">
                    <div className="card-header bg-primary text-white">
                      <h6 className="mb-0"><i className="bi bi-trophy me-2"></i>Score</h6>
                    </div>
                    <div className="card-body">
                      <h3 className="text-center">{score || 0} / {exam?.totalMarks || total_questions || 0}</h3>
                      <p className="text-center">Percentage: {exam?.totalMarks ? ((score / exam.totalMarks) * 100).toFixed(2) : 0}%</p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="card mb-3">
                <div className="card-header bg-danger text-white">
                  <h6 className="mb-0"><i className="bi bi-exclamation-triangle me-2"></i>Violations Summary</h6>
                </div>
                <div className="card-body">
                  <table className="table table-striped">
                    <thead>
                      <tr>
                        <th>Violation Type</th>
                        <th>Count</th>
                      </tr>
                    </thead>
                    <tbody>
                      {Object.entries(violation_counts || {}).map(([key, value]) => (
                        <tr key={key}>
                          <td>{key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}</td>
                          <td>{value}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {snapshots.length > 0 && (
                <div className="card">
                  <div className="card-header bg-secondary text-white">
                    <h6 className="mb-0"><i className="bi bi-camera me-2"></i>Violation Screenshots ({snapshots.length})</h6>
                  </div>
                  <div className="card-body">
                    <div className="row">
                      {snapshots.map((snap, index) => (
                        <div key={index} className="col-md-6 mb-3">
                          <div className="card">
                            <div className="card-body">
                              <h6>Screenshot {index + 1}</h6>
                              <p><strong>Timestamp:</strong> {snap.timestamp ? new Date(snap.timestamp).toLocaleString() : 'N/A'}</p>
                              <p><strong>Violations:</strong> {snap.violations && snap.violations.length > 0 ? snap.violations.join(', ') : 'None'}</p>
                              {snap.detections && (
                                <div>
                                  <p><strong>Detections:</strong></p>
                                  <ul>
                                    <li>Person Count: {snap.detections.person_count || 0}</li>
                                    <li>Face Count: {snap.detections.face_count || 0}</li>
                                    <li>Gaze: {snap.detections.gaze || 'N/A'}</li>
                                    {snap.detections.detected_objects && snap.detections.detected_objects.length > 0 && (
                                      <li>Objects: {snap.detections.detected_objects.join(', ')}</li>
                                    )}
                                  </ul>
                                </div>
                              )}
                              {snap.image_url && (
                                <div>
                                  <img src={snap.image_url} alt={`Screenshot ${index + 1}`} style={{width: '100%', maxHeight: '200px', objectFit: 'cover'}} />
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ResultPDF;
